# Change Log

## [0.1.5] - 2020-04-09

- Fix `fallback_message` error.

[0.1.5]: https://pypi.org/project/hipo-drf-exceptions/0.1.5/

## [0.1.4] - 2020-04-03

- Fix `fallback_message` of Django [ValidationError](https://github.com/Hipo/hipo-drf-exceptions/issues/14).

[0.1.4]: https://pypi.org/project/hipo-drf-exceptions/0.1.4/

## [0.1.3] - 2019-12-09

- Fix fallback_message of Django [ValidationError](https://github.com/Hipo/hipo-drf-exceptions/issues/10).

[0.1.3]: https://pypi.org/project/hipo-drf-exceptions/0.1.3/

## [0.1.2] - 2019-10-17

- Fix [bulk exceptions](https://github.com/Hipo/hipo-drf-exceptions/issues/9).

[0.1.2]: https://pypi.org/project/hipo-drf-exceptions/0.1.2/

## [0.1.1] - 2019-09-05

- Fix fallback message of [nested exceptions](https://github.com/Hipo/hipo-drf-exceptions/issues/4).

[0.1.1]: https://pypi.org/project/hipo-drf-exceptions/0.1.1/


## [0.1.0] - 2019-07-03

Initial release

[0.1.0]: https://pypi.org/project/hipo-drf-exceptions/0.1.0/
